### ISSUE TITLE
Add (meaningful) Comments

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [Aatmaj-Zephyr/handtype#10]
Add comments and relevant documentation for the code explaining every aspect of the code.

Note- for PR to be accepted for hacktoberfest, it must have a significant contribution and must not by just cut/copy/paste or  blind AI-generated work.

👍🏻

**Comment by BkPankaj** [comment]
As I can see there is already comments added in handtype.ipynb. So what comments you are talking about? I am interested in your project can you just provide this clarification.

**Comment by Aatmaj-Zephyr** [comment]
Need to add more comments that explain the code better. And also explain the parameters used. Eg line space etc

**Comment by BkPankaj** [comment]
Yaa I am working on it. Thank you for the clarification.

**Comment by BkPankaj** [comment]
@Aatmaj-Zephyr please verify and merge the changes
