### ISSUE TITLE
Add workflow to enforce standards in code

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [Aatmaj-Zephyr/handtype#11]
Add static code analysis for enforcing pep-8 standards for maintaining this repository using GitHub actions.

Note- for PR to be accepted for hacktoberfest, it must have a significant contribution and must not by just cut/copy/paste or blind AI-generated work.

👍🏻

**Comment by CaiqueCoelho** [comment]
I would like to work on this. Can you assign it to me?

**Comment by Aatmaj-Zephyr** [comment]
Done👍🏻

**Comment by CaiqueCoelho** [comment]
I would like to work on this. Can you assign it to me? Also, can this be part of Hacktoberfest, please?

**Comment by CaiqueCoelho** [comment]
Hey @Aatmaj-Zephyr I just created a PR for this https://github.com/Aatmaj-Zephyr/handtype/pull/13 could you review, please? Also, I would be very happy if this PR could be part of Hacktoberfest please
