### ISSUE TITLE
Improve Readme.md

### ISSUE THREAD

**Issue by ayushsarode** [Aatmaj-Zephyr/handtype#8]
I want to enhance the ```Readme.md```.
Considering:

1. Table of content
2. Visitor Counter 
3. Steps to contribute

**Comment by Aatmaj-Zephyr** [comment]
Thanks @ayushsarode 

However, just keep in mind that for an PR to be eligible in hacktoberfest, there must be a significant amount of contribution. So please enhance accordingly👍🏻

**Comment by ayushsarode** [comment]
Sure!
